### ISSUE TITLE
🔥 feat: 4개 타입에 대한 컴포넌트 개발

### ISSUE THREAD

**Issue by widrns15** [widrns15/fe-sprint-coz-shopping#5]
## 📁 이슈 내용

홈페이지 컴포넌트 블럭 구현 및 기능 추가

## 📝 작업 내용

- 마크업 작업
  - 각 타입 별로 컴포넌트를 따로 만들어 관리할지, 1개의 컴포넌트로 4개 타입을 전달인자로 받아 렌더링 시 타입별로 다른 UI를 적용하도록 할지 결정하기 (플래닝 시점)
  - 1개의 컴포넌트로 4개 타입을 전달인자로 받아 다른 UI를 적용하기로 결정
- browser db를 이용해 북마크 기능 구현 및 관리
  - 어떤 browser db를 이용할지 결정 필요 (플래닝 시점)

## 📍ETC
기타사항

**Comment by Jeong-hae-rim** [comment]
얼마 정도의 시간이 드는 지도 예측해보고 제목에다 시간을 작성해보세요!

기간 내에 조금 더 개발할 수 있겠다 싶으시면 Backlog에 들어있는 것들을 Todo로 끌어오셔도 좋습니다!
